In [1]:
v1 = [2,4,6]

In [2]:
v1

[2, 4, 6]

In [3]:
import numpy as np 

In [5]:
v2 = np.ones(3)
v2

array([1., 1., 1.])

In [7]:
v3 = np.array([1,3,5])
v3

array([1, 3, 5])

In [8]:
v4 = np.arange(1,8)
v4

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
v4 + 5

array([ 6,  7,  8,  9, 10, 11, 12])

In [10]:
v4 * 5

array([ 5, 10, 15, 20, 25, 30, 35])

In [11]:
v1 + 5

TypeError: can only concatenate list (not "int") to list

In [12]:
v1 * 5

[2, 4, 6, 2, 4, 6, 2, 4, 6, 2, 4, 6, 2, 4, 6]

In [13]:
v4 - 1

array([0, 1, 2, 3, 4, 5, 6])

In [14]:
v1 - 1

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [15]:
v3 + v2

array([2., 4., 6.])

In [16]:
v1 + v2

array([3., 5., 7.])

In [17]:
v5 = [1,1,1]
v1 + v5

[2, 4, 6, 1, 1, 1]

In [18]:
x = np.arange(1,5)
y = np.array([2,4,6,8])

In [19]:
x, y

(array([1, 2, 3, 4]), array([2, 4, 6, 8]))

In [20]:
type(x) 

numpy.ndarray

In [21]:
x+y

array([ 3,  6,  9, 12])

In [22]:
x-y

array([-1, -2, -3, -4])

In [23]:
x*2

array([2, 4, 6, 8])

In [24]:
y*3

array([ 6, 12, 18, 24])

In [25]:
sum(x*y)

60

In [26]:
np.dot(x,y)

60

In [29]:
v1 = np.array([3,4])
v2 = np.array([4,-3])
np.dot(v1,v2)

0

In [30]:
np.linalg.norm(x)

5.477225575051661

In [31]:
np.linalg.norm([3,4])

5.0

In [36]:
A = np.array([[1, 3, 2],
              [1, 0, 0],
              [1, 2, 2]])


In [37]:
A * 2

array([[2, 6, 4],
       [2, 0, 0],
       [2, 4, 4]])

In [38]:
B = np.array([[1, 0, 5],
              [7, 5, 0],
              [2, 1, 1]])

In [39]:
A + B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

In [40]:
A - B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

In [41]:
A.shape

(3, 3)

In [42]:
v3.shape

(3,)

In [43]:
A.size

9

In [44]:
len(A)

3

In [46]:
A = np.arange(1, 13).reshape(3, 4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
B = np.arange(8).reshape(4,2)
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [48]:
A @ B

array([[ 40,  50],
       [ 88, 114],
       [136, 178]])

In [53]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [55]:
A = np.array([[4, 7], 
             [2, 6]])
A

array([[4, 7],
       [2, 6]])

In [56]:
A @ I

array([[4., 7.],
       [2., 6.]])

In [57]:
np.linalg.det(A)

10.000000000000002

In [61]:
A = np.array([[1, 2, 3], 
             [1, 1, 1],
            [0,1,-1]])

In [62]:
np.linalg.det(A)

3.0000000000000004

In [64]:
A = np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [65]:
np.transpose(A)

array([[0, 2, 4],
       [1, 3, 5]])

In [66]:
A = np.array([[4, 7],
              [2, 6]])

In [67]:
A_inv = np.linalg.inv(A)
A_inv 

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [69]:
A = np.array([[2,0,1],
              [1,1,-4],
             [3,7,-3]])

In [70]:
A_inv = np.linalg.inv(A)
A_inv 

array([[ 0.46296296,  0.12962963, -0.01851852],
       [-0.16666667, -0.16666667,  0.16666667],
       [ 0.07407407, -0.25925926,  0.03703704]])